/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTrackRouteImport } from './routes/_public.track'
import { Route as PublicProductsRouteImport } from './routes/_public.products'
import { Route as PublicCheckoutRouteImport } from './routes/_public.checkout'
import { Route as PublicCartRouteImport } from './routes/_public.cart'
import { Route as PublicAuthRouteImport } from './routes/_public.auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as PublicProductsSlugRouteImport } from './routes/_public.products.$slug'
import { Route as PublicOrderConfirmationIdRouteImport } from './routes/_public.order-confirmation.$id'
import { Route as PublicCategoriesSlugRouteImport } from './routes/_public.categories.$slug'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminIncompleteRouteImport } from './routes/_authenticated/admin.incomplete'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminChatRouteImport } from './routes/_authenticated/admin.chat'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated/account.wishlist'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'
import { Route as ApiPublicPaymentCallbackRouteImport } from './routes/api/public/payment.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTrackRoute = PublicTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicOrderConfirmationIdRoute =
  PublicOrderConfirmationIdRouteImport.update({
    id: '/order-confirmation/$id',
    path: '/order-confirmation/$id',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicCategoriesSlugRoute = PublicCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncompleteRoute =
  AuthenticatedAdminIncompleteRouteImport.update({
    id: '/incomplete',
    path: '/incomplete',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatRoute = AuthenticatedAdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const ApiPublicPaymentCallbackRoute =
  ApiPublicPaymentCallbackRouteImport.update({
    id: '/api/public/payment/callback',
    path: '/api/public/payment/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auth': typeof PublicAuthRoute
  '/cart': typeof PublicCartRoute
  '/checkout': typeof PublicCheckoutRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/track': typeof PublicTrackRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/incomplete': typeof AuthenticatedAdminIncompleteRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/categories/$slug': typeof PublicCategoriesSlugRoute
  '/order-confirmation/$id': typeof PublicOrderConfirmationIdRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payment/callback': typeof ApiPublicPaymentCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth': typeof PublicAuthRoute
  '/cart': typeof PublicCartRoute
  '/checkout': typeof PublicCheckoutRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/track': typeof PublicTrackRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/incomplete': typeof AuthenticatedAdminIncompleteRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/categories/$slug': typeof PublicCategoriesSlugRoute
  '/order-confirmation/$id': typeof PublicOrderConfirmationIdRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/payment/callback': typeof ApiPublicPaymentCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_public/auth': typeof PublicAuthRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/_public/track': typeof PublicTrackRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/chat': typeof AuthenticatedAdminChatRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/incomplete': typeof AuthenticatedAdminIncompleteRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_public/categories/$slug': typeof PublicCategoriesSlugRoute
  '/_public/order-confirmation/$id': typeof PublicOrderConfirmationIdRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payment/callback': typeof ApiPublicPaymentCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/track'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/customers'
    | '/admin/incomplete'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/categories/$slug'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/api/public/payment/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/track'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/customers'
    | '/admin/incomplete'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/categories/$slug'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/api/public/payment/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_public/auth'
    | '/_public/cart'
    | '/_public/checkout'
    | '/_public/products'
    | '/_public/track'
    | '/_public/'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/wishlist'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/chat'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/incomplete'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
    | '/_public/categories/$slug'
    | '/_public/order-confirmation/$id'
    | '/_public/products/$slug'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/api/public/payment/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicPaymentCallbackRoute: typeof ApiPublicPaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/track': {
      id: '/_public/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof PublicTrackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/order-confirmation/$id': {
      id: '/_public/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof PublicOrderConfirmationIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/categories/$slug': {
      id: '/_public/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof PublicCategoriesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incomplete': {
      id: '/_authenticated/admin/incomplete'
      path: '/incomplete'
      fullPath: '/admin/incomplete'
      preLoaderRoute: typeof AuthenticatedAdminIncompleteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat': {
      id: '/_authenticated/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AuthenticatedAdminChatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/public/payment/callback': {
      id: '/api/public/payment/callback'
      path: '/api/public/payment/callback'
      fullPath: '/api/public/payment/callback'
      preLoaderRoute: typeof ApiPublicPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminChatRoute: typeof AuthenticatedAdminChatRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminIncompleteRoute: typeof AuthenticatedAdminIncompleteRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminChatRoute: AuthenticatedAdminChatRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminIncompleteRoute: AuthenticatedAdminIncompleteRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicProductsRouteChildren {
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsSlugRoute: PublicProductsSlugRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRoute
  PublicCartRoute: typeof PublicCartRoute
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicTrackRoute: typeof PublicTrackRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCategoriesSlugRoute: typeof PublicCategoriesSlugRoute
  PublicOrderConfirmationIdRoute: typeof PublicOrderConfirmationIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRoute,
  PublicCartRoute: PublicCartRoute,
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicTrackRoute: PublicTrackRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCategoriesSlugRoute: PublicCategoriesSlugRoute,
  PublicOrderConfirmationIdRoute: PublicOrderConfirmationIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicPaymentCallbackRoute: ApiPublicPaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
